"""
Automatically generated by Zserio Python extension version 2.0.0.
"""

import enum

class Language(enum.Enum):
    CPP = 0
    JAVA = 1
    PYTHON = 2
    JS = 3

    @classmethod
    def fromReader(cls, reader):
        return cls(reader.readBits(2))

    def bitSizeOf(self, _bitPosition=0):
        return 2

    def initializeOffsets(self, bitPosition):
        return bitPosition + self.bitSizeOf(bitPosition)

    def write(self, writer):
        writer.writeBits(self.value, 2)
