"""
Automatically generated by Zserio Python extension version 2.2.0.
Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
"""

import enum
import typing
import zserio

class Language(enum.Enum):
    CPP = 0
    JAVA = 1
    PYTHON = 2
    JS = 3

    @classmethod
    def fromReader(cls: typing.Type['Language'], reader: zserio.BitStreamReader) -> 'Language':
        return cls(reader.readBits(2))

    def bitSizeOf(self, _bitPosition: int = 0) -> int:
        return 2

    def initializeOffsets(self, bitPosition: int) -> int:
        return bitPosition + self.bitSizeOf(bitPosition)

    def write(self, writer: zserio.BitStreamWriter) -> None:
        writer.writeBits(self.value, 2)
