# Automatically generated by Zserio Python generator version 1.0.5 using Zserio core 2.16.1.
# Generator setup: writerCode, pubsubCode, serviceCode, sqlCode

from __future__ import annotations

import typing
import zserio

class Role(zserio.Enum):
    DEVELOPER = 0
    TEAM_LEAD = 1
    CTO = 2

    @classmethod
    def from_name(cls: typing.Type['Role'], item_name: str) -> 'Role':
        if item_name == 'DEVELOPER':
            item = Role.DEVELOPER
        elif item_name == 'TEAM_LEAD':
            item = Role.TEAM_LEAD
        elif item_name == 'CTO':
            item = Role.CTO
        else:
            raise zserio.PythonRuntimeException(f"Enum item '{item_name}' doesn't exist in enum 'Role'!")

        return item

    @classmethod
    def from_reader(cls: typing.Type['Role'], reader: zserio.BitStreamReader) -> 'Role':
        return cls(reader.read_bits(8))

    def __hash__(self) -> int:
        result = zserio.hashcode.HASH_SEED
        result = zserio.hashcode.calc_hashcode_int32(result, self.value)
        return result

    def bitsizeof(self, _bitposition: int = 0) -> int:
        return 8

    def initialize_offsets(self, bitposition: int = 0) -> int:
        return bitposition + self.bitsizeof(bitposition)

    def write(self, writer: zserio.BitStreamWriter) -> None:
        writer.write_bits(self.value, 8)
