"""
Automatically generated by Zserio Python extension version 2.2.0.
Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
"""

import enum
import typing
import zserio

class Role(enum.Enum):
    DEVELOPER = 0
    TEAM_LEAD = 1
    CTO = 2

    @classmethod
    def fromReader(cls: typing.Type['Role'], reader: zserio.BitStreamReader) -> 'Role':
        return cls(reader.readBits(8))

    def bitSizeOf(self, _bitPosition: int = 0) -> int:
        return 8

    def initializeOffsets(self, bitPosition: int) -> int:
        return bitPosition + self.bitSizeOf(bitPosition)

    def write(self, writer: zserio.BitStreamWriter) -> None:
        writer.writeBits(self.value, 8)
